In [30]:
import pandas as pd
colunas=['id_seq', 'Identificação da Compra', 'Número do Item', 'Modalidade', 'Código do CATMAT', 'Item', 'Descrição',
         'Unidade de Fornecimento', 'Quantidade Ofertada', 'Valor Unitário', 'Fornecedor', 'Órgão', 'UASG - Unidade Gestora',
         'Objeto da compra', 'Valor proposto unitário', 'Forma da compra', 'Marca', 'Data resultado', 'CNPJ/CPF Fornecedor',
         'Porte Fornecedor', 'Orgão Superior', 'Número UASG', 'Ano compra', 'Painel', 'Data da Compra', 'Valor']

painel = pd.read_csv('csv/painel_precos.csv', error_bad_lines=False, sep=';', index_col=False, header=0, names=colunas)
painel.to_excel('excel/painel.xlsx', index=False)
display(painel.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_seq                   49 non-null     int64
 1   Identificação da Compra  49 non-null     object
 2   Número do Item           49 non-null     int64
 3   Modalidade               49 non-null     object
 4   Código do CATMAT         49 non-null     int64
 5   Item                     49 non-null     object
 6   Descrição                49 non-null     object
 7   Unidade de Fornecimento  49 non-null     object
 8   Quantidade Ofertada      49 non-null     float64
 9   Valor Unitário           49 non-null     object
 10  Fornecedor               49 non-null     object
 11  Órgão                    49 non-null     object
 12  UASG - Unidade Gestora   49 non-null     object
 13  Objeto da compra         49 non-null     object
 14  Valor proposto unitário  49 non-null     object
 15  Forma da compra          49 non-null     object
 16  Marca                    49 non-null     object
 17  Data resultado           49 non-null     object
 18  CNPJ/CPF Fornecedor      49 non-null     int64
 19  Porte Fornecedor         49 non-null     object
 20  Orgão Superior           49 non-null     object
 21  Número UASG              49 non-null     int64
 22  Ano compra               49 non-null     int64
 23  Painel                   49 non-null     int64
 24  Data da Compra           49 non-null     object
 25  Valor                    49 non-null     object
dtypes: float64(1), int64(7), object(18)
memory usage: 10.1+ KB

b'Skipping line 41: expected 26 fields, saw 27\n'

None

In [50]:
mod_avn = pd.DataFrame()
mod_avn['id_compra'] = "0" + painel['UASG - Unidade Gestora'].str[0:5] + "0" + painel['Painel'].astype(str) + painel['Identificação da Compra'].str.replace('/','')
mod_avn['id_compra_item'] = mod_avn['id_compra'] + painel['Número do Item'].astype(str)
mod_avn['barra'] = ''
mod_avn

            id_compra        id_compra_item barra
0   02402207000012021    024022070000120211
1   09842205000012021   0984220500001202141
2   09875005000152021    098750050001520219
3   01600105000262020   0160010500026202049
4   09261905000092020    092619050000920204
5   09801405000262021   0980140500026202163
6   09837105000182021   0983710500018202199
7   09847605000672021   0984760500067202110
8   01604206000412021    016042060004120211
9   09809505000202021   0980950500020202157
10  09801405000262021   0980140500026202120
11  09801205000142021   0980120500014202161
12  04559705000672021  04559705000672021153
13  01604706000932021    016047060009320214
14  02550106000032021    025501060000320215
15  09894005000662021   0989400500066202159
16  09899805000252021   0989980500025202138
17  09884605001042020    098846050010420207
18  01602405000262021  01602405000262021164
19  01600105000262020   0160010500026202028
20  01540605000042021   0154060500004202144
21  09273505000152021   0927350500015202158
22  09803805000112021  09803805000112021163
23  09859005000422021   0985900500042202116
24  01603805000212020  01603805000212020116
25  09877905000262021   0987790500026202169
26  07953805000032021   0795380500003202152
27  09812205000082021    098122050000820212
28  09847305000132021  09847305000132021171
29  09807605000122021   0980760500012202141
30  09804905000202021   0980490500020202169
31  01600206000192021    016002060001920211
32  01603605000032021   0160360500003202124
33  09816405000142021  09816405000142021112
34  01602506004092021    016025060040920211
35  01550105000182021   0155010500018202118
36  01602506000512021    016025060005120211
37  09816405000142021  09816405000142021100
38  01600905000242020  01600905000242020135
39  01602105000092021  01602105000092021110
40  09876805000192021   0987680500019202136
41  01600405000012021  01600405000012021147
42  01581205000012021   0158120500001202134
43  01583205000492020   0158320500049202050
44  02550006000112020    025500060001120203
45  01600805000032021  01600805000032021109
46  01206205000022021   0120620500002202115
47  09259505000182021   0925950500018202116
48  09847205000352021   0984720500035202118